version: 0.1

phases:
  install:
    commands:
      - echo Installing Node.js and Yarn...
      - apt-get update
      - apt-get install -y nodejs
      - apt-get install -y yarn 

  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli

  build:
    commands:
      - cd hello-angular
      - ng build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/hello-angular
